import 'package:school_api_client/school_api_client.dart';

/// Identifies which native application owns a registration.
enum SchoolMobileApplication { family, staff }

/// Native operating systems currently supported by MOB-01.
enum SchoolMobilePlatform { android, ios }

/// Provider that issued the notification token.
enum SchoolPushProvider { firebase, apns }

/// Separates development notification credentials from production credentials.
enum SchoolPushEnvironment { development, production }

/// A push token that deliberately redacts itself from logs and diagnostics.
final class SchoolPushToken {
  SchoolPushToken(String value) : value = value.trim() {
    if (this.value.isEmpty || this.value.length > 4096) {
      throw const DeviceSessionContractException('DEVICE_PUSH_TOKEN_INVALID');
    }
  }

  final String value;

  @override
  String toString() => 'SchoolPushToken([REDACTED])';
}

/// Account-scoped input for registering an app-generated installation.
///
/// [installationId] must be generated by the application. Hardware identifiers,
/// advertising identifiers, phone numbers, email addresses and device names are
/// not part of this contract.
final class DeviceSessionRegistration {
  DeviceSessionRegistration({
    required this.appVersion,
    required this.application,
    required String installationId,
    required this.notificationEnvironment,
    required this.platform,
    required this.pushProvider,
    required this.pushToken,
  }) : installationId = installationId.trim() {
    if (!_installationPattern.hasMatch(this.installationId)) {
      throw const DeviceSessionContractException(
        'DEVICE_INSTALLATION_ID_INVALID',
      );
    }
    if (appVersion.trim().isEmpty || appVersion.length > 64) {
      throw const DeviceSessionContractException('DEVICE_APP_VERSION_INVALID');
    }
  }

  static final RegExp _installationPattern = RegExp(r'^[A-Za-z0-9_-]{16,128}$');

  final String installationId;
  final SchoolMobileApplication application;
  final SchoolMobilePlatform platform;
  final String appVersion;
  final SchoolPushProvider pushProvider;
  final SchoolPushEnvironment notificationEnvironment;
  final SchoolPushToken pushToken;

  Map<String, Object?> toJson() => <String, Object?>{
    'installationId': installationId,
    'application': application.name,
    'platform': platform.name,
    'appVersion': appVersion.trim(),
    'pushProvider': pushProvider.name,
    'notificationEnvironment': notificationEnvironment.name,
    'pushToken': pushToken.value,
  };

  @override
  String toString() =>
      'DeviceSessionRegistration(application: ${application.name}, '
      'platform: ${platform.name}, pushToken: [REDACTED])';
}

final class RegisteredDeviceSession {
  const RegisteredDeviceSession({
    required this.deviceSessionId,
    required this.installationId,
    required this.registeredAt,
    required this.revision,
  });

  final String deviceSessionId;
  final String installationId;
  final DateTime registeredAt;
  final int revision;
}

final class DeviceSessionContractException implements Exception {
  const DeviceSessionContractException(this.code);

  final String code;

  @override
  String toString() => 'DeviceSessionContractException($code)';
}

/// Client-only contract for the future server-owned device-session endpoint.
final class DeviceSessionApi {
  const DeviceSessionApi(this._client);

  static const registrationPath = '/v1/mobile/device-sessions';

  final SchoolApiClient _client;

  Future<RegisteredDeviceSession> register({
    required String correlationId,
    required String idempotencyKey,
    required DeviceSessionRegistration registration,
  }) async {
    final response = await _client.postJson(
      registrationPath,
      body: registration.toJson(),
      context: ApiRequestContext.accountScoped(correlationId: correlationId),
      idempotencyKey: idempotencyKey,
    );
    return _decode(response);
  }

  Future<void> revoke({
    required String correlationId,
    required String deviceSessionId,
    required String idempotencyKey,
  }) async {
    final normalizedId = deviceSessionId.trim();
    if (normalizedId.isEmpty || normalizedId.length > 256) {
      throw const DeviceSessionContractException('DEVICE_SESSION_ID_INVALID');
    }
    final encodedId = Uri.encodeComponent(normalizedId);
    await _client.postJson(
      '$registrationPath/$encodedId/revoke',
      body: const <String, Object?>{},
      context: ApiRequestContext.accountScoped(correlationId: correlationId),
      idempotencyKey: idempotencyKey,
    );
  }

  RegisteredDeviceSession _decode(Map<String, Object?> json) {
    try {
      final registeredAt = DateTime.parse(
        _requiredString(json, 'registeredAt'),
      );
      final revision = json['revision'];
      if (revision is! int || revision < 1) {
        throw const FormatException('DEVICE_SESSION_REVISION_INVALID');
      }
      return RegisteredDeviceSession(
        deviceSessionId: _requiredString(json, 'deviceSessionId'),
        installationId: _requiredString(json, 'installationId'),
        registeredAt: registeredAt.toUtc(),
        revision: revision,
      );
    } on FormatException {
      throw const SchoolApiException(
        code: 'INVALID_DEVICE_SESSION_RESPONSE',
        message: 'The device registration response could not be validated.',
      );
    }
  }

  String _requiredString(Map<String, Object?> json, String key) {
    final value = json[key];
    if (value is! String || value.trim().isEmpty) {
      throw FormatException('DEVICE_SESSION_FIELD_REQUIRED:$key');
    }
    return value.trim();
  }
}
