CREATE SCHEMA IF NOT EXISTS ledger;
GRANT USAGE ON SCHEMA ledger TO app_runtime;

CREATE TABLE IF NOT EXISTS ledger.book (
  tenant_id uuid NOT NULL,
  legal_entity_id uuid NOT NULL,
  book_id uuid NOT NULL DEFAULT gen_random_uuid(),
  code citext NOT NULL,
  name text NOT NULL,
  base_currency char(3) NOT NULL CHECK (base_currency ~ '^[A-Z]{3}$'),
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, legal_entity_id, book_id),
  UNIQUE (tenant_id, legal_entity_id, code),
  FOREIGN KEY (tenant_id, legal_entity_id) REFERENCES tenancy.legal_entity (tenant_id, legal_entity_id)
);

CREATE TABLE IF NOT EXISTS ledger.fiscal_period (
  tenant_id uuid NOT NULL,
  legal_entity_id uuid NOT NULL,
  book_id uuid NOT NULL,
  fiscal_period_id uuid NOT NULL DEFAULT gen_random_uuid(),
  period_code text NOT NULL,
  starts_on date NOT NULL,
  ends_on date NOT NULL,
  status text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'closed')),
  closed_by text,
  closed_at timestamptz,
  reopened_by text,
  reopened_at timestamptz,
  reopen_reason text,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, legal_entity_id, fiscal_period_id),
  UNIQUE (tenant_id, legal_entity_id, book_id, period_code),
  CHECK (starts_on <= ends_on),
  FOREIGN KEY (tenant_id, legal_entity_id, book_id) REFERENCES ledger.book (tenant_id, legal_entity_id, book_id)
);

CREATE TABLE IF NOT EXISTS ledger.account (
  tenant_id uuid NOT NULL,
  legal_entity_id uuid NOT NULL,
  book_id uuid NOT NULL,
  account_id uuid NOT NULL DEFAULT gen_random_uuid(),
  account_code citext NOT NULL,
  account_name text NOT NULL,
  account_type text NOT NULL CHECK (account_type IN ('asset', 'liability', 'equity', 'income', 'expense')),
  natural_balance text NOT NULL CHECK (natural_balance IN ('debit', 'credit')),
  parent_account_id uuid,
  control_account boolean NOT NULL DEFAULT false,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, legal_entity_id, account_id),
  UNIQUE (tenant_id, legal_entity_id, book_id, account_code),
  CHECK (
    (account_type IN ('asset', 'expense') AND natural_balance = 'debit') OR
    (account_type IN ('liability', 'equity', 'income') AND natural_balance = 'credit')
  ),
  FOREIGN KEY (tenant_id, legal_entity_id, book_id) REFERENCES ledger.book (tenant_id, legal_entity_id, book_id),
  FOREIGN KEY (tenant_id, legal_entity_id, parent_account_id) REFERENCES ledger.account (tenant_id, legal_entity_id, account_id)
);

CREATE TABLE IF NOT EXISTS ledger.dimension (
  tenant_id uuid NOT NULL,
  legal_entity_id uuid NOT NULL,
  dimension_id uuid NOT NULL DEFAULT gen_random_uuid(),
  code citext NOT NULL,
  name text NOT NULL,
  required boolean NOT NULL DEFAULT false,
  active boolean NOT NULL DEFAULT true,
  PRIMARY KEY (tenant_id, legal_entity_id, dimension_id),
  UNIQUE (tenant_id, legal_entity_id, code)
);

CREATE TABLE IF NOT EXISTS ledger.posting_rule_version (
  tenant_id uuid NOT NULL,
  legal_entity_id uuid NOT NULL,
  posting_rule_id uuid NOT NULL,
  version integer NOT NULL CHECK (version > 0),
  trigger_name text NOT NULL,
  rule_document jsonb NOT NULL,
  effective_from timestamptz NOT NULL,
  effective_to timestamptz,
  active boolean NOT NULL DEFAULT true,
  created_by text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, legal_entity_id, posting_rule_id, version),
  CHECK (effective_to IS NULL OR effective_to > effective_from)
);

CREATE TABLE IF NOT EXISTS ledger.journal_entry (
  tenant_id uuid NOT NULL,
  legal_entity_id uuid NOT NULL,
  book_id uuid NOT NULL,
  fiscal_period_id uuid NOT NULL,
  journal_entry_id uuid NOT NULL DEFAULT gen_random_uuid(),
  entry_number bigint GENERATED BY DEFAULT AS IDENTITY,
  entry_date date NOT NULL,
  description text NOT NULL,
  source_document_type text NOT NULL,
  source_document_id text NOT NULL,
  correlation_id text NOT NULL,
  idempotency_key text NOT NULL,
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'posted')),
  created_by text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  posted_by text,
  posted_at timestamptz,
  reversal_of uuid,
  reversal_reason text,
  PRIMARY KEY (tenant_id, legal_entity_id, journal_entry_id),
  UNIQUE (tenant_id, legal_entity_id, idempotency_key),
  UNIQUE (tenant_id, legal_entity_id, book_id, entry_number),
  FOREIGN KEY (tenant_id, legal_entity_id, book_id) REFERENCES ledger.book (tenant_id, legal_entity_id, book_id),
  FOREIGN KEY (tenant_id, legal_entity_id, fiscal_period_id) REFERENCES ledger.fiscal_period (tenant_id, legal_entity_id, fiscal_period_id),
  FOREIGN KEY (tenant_id, legal_entity_id, reversal_of) REFERENCES ledger.journal_entry (tenant_id, legal_entity_id, journal_entry_id),
  CHECK ((status = 'draft' AND posted_by IS NULL AND posted_at IS NULL) OR (status = 'posted' AND posted_by IS NOT NULL AND posted_at IS NOT NULL)),
  CHECK (reversal_of IS NULL OR length(trim(reversal_reason)) >= 8)
);

CREATE TABLE IF NOT EXISTS ledger.journal_line (
  tenant_id uuid NOT NULL,
  legal_entity_id uuid NOT NULL,
  journal_entry_id uuid NOT NULL,
  journal_line_id uuid NOT NULL DEFAULT gen_random_uuid(),
  line_number integer NOT NULL CHECK (line_number > 0),
  account_id uuid NOT NULL,
  side text NOT NULL CHECK (side IN ('debit', 'credit')),
  amount_minor bigint NOT NULL CHECK (amount_minor > 0),
  currency char(3) NOT NULL CHECK (currency ~ '^[A-Z]{3}$'),
  description text,
  dimensions jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(dimensions) = 'object'),
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, legal_entity_id, journal_line_id),
  UNIQUE (tenant_id, legal_entity_id, journal_entry_id, line_number),
  FOREIGN KEY (tenant_id, legal_entity_id, journal_entry_id) REFERENCES ledger.journal_entry (tenant_id, legal_entity_id, journal_entry_id),
  FOREIGN KEY (tenant_id, legal_entity_id, account_id) REFERENCES ledger.account (tenant_id, legal_entity_id, account_id)
);

CREATE INDEX IF NOT EXISTS ledger_entry_source_idx ON ledger.journal_entry (tenant_id, legal_entity_id, source_document_type, source_document_id);
CREATE INDEX IF NOT EXISTS ledger_entry_period_date_idx ON ledger.journal_entry (tenant_id, legal_entity_id, fiscal_period_id, entry_date) WHERE status = 'posted';
CREATE INDEX IF NOT EXISTS ledger_line_account_idx ON ledger.journal_line (tenant_id, legal_entity_id, account_id, journal_entry_id);

CREATE OR REPLACE FUNCTION ledger.reject_posted_entry_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF OLD.status = 'posted' THEN
    RAISE EXCEPTION 'FIN_POSTED_JOURNAL_IMMUTABLE' USING ERRCODE = '23514';
  END IF;
  RETURN COALESCE(NEW, OLD);
END;
$$;

DROP TRIGGER IF EXISTS journal_entry_immutable_when_posted ON ledger.journal_entry;
CREATE TRIGGER journal_entry_immutable_when_posted
  BEFORE UPDATE OR DELETE ON ledger.journal_entry
  FOR EACH ROW EXECUTE FUNCTION ledger.reject_posted_entry_mutation();

CREATE OR REPLACE FUNCTION ledger.reject_posted_line_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE parent_status text;
BEGIN
  SELECT status INTO parent_status
  FROM ledger.journal_entry
  WHERE tenant_id = OLD.tenant_id
    AND legal_entity_id = OLD.legal_entity_id
    AND journal_entry_id = OLD.journal_entry_id;
  IF parent_status = 'posted' THEN
    RAISE EXCEPTION 'FIN_POSTED_JOURNAL_LINE_IMMUTABLE' USING ERRCODE = '23514';
  END IF;
  RETURN COALESCE(NEW, OLD);
END;
$$;

DROP TRIGGER IF EXISTS journal_line_immutable_when_posted ON ledger.journal_line;
CREATE TRIGGER journal_line_immutable_when_posted
  BEFORE UPDATE OR DELETE ON ledger.journal_line
  FOR EACH ROW EXECUTE FUNCTION ledger.reject_posted_line_mutation();

CREATE OR REPLACE FUNCTION ledger.post_journal_entry(p_journal_entry_id uuid, p_posted_by text) RETURNS ledger.journal_entry
LANGUAGE plpgsql SECURITY DEFINER SET search_path = ledger, pg_temp AS $$
DECLARE
  target ledger.journal_entry;
  period_status text;
  debit_total bigint;
  credit_total bigint;
  line_count integer;
  currency_count integer;
BEGIN
  SELECT * INTO target
  FROM ledger.journal_entry
  WHERE tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid
    AND journal_entry_id = p_journal_entry_id
  FOR UPDATE;
  IF target.journal_entry_id IS NULL THEN RAISE EXCEPTION 'FIN_NOT_FOUND:journal'; END IF;
  IF target.status = 'posted' THEN RETURN target; END IF;
  IF target.created_by = p_posted_by THEN RAISE EXCEPTION 'FIN_SOD_VIOLATION:journal-create-post'; END IF;

  SELECT status INTO period_status
  FROM ledger.fiscal_period
  WHERE tenant_id = target.tenant_id
    AND legal_entity_id = target.legal_entity_id
    AND fiscal_period_id = target.fiscal_period_id;
  IF period_status <> 'open' THEN RAISE EXCEPTION 'FIN_PERIOD_CLOSED'; END IF;

  SELECT
    count(*),
    count(DISTINCT currency),
    COALESCE(sum(amount_minor) FILTER (WHERE side = 'debit'), 0),
    COALESCE(sum(amount_minor) FILTER (WHERE side = 'credit'), 0)
  INTO line_count, currency_count, debit_total, credit_total
  FROM ledger.journal_line
  WHERE tenant_id = target.tenant_id
    AND legal_entity_id = target.legal_entity_id
    AND journal_entry_id = target.journal_entry_id;

  IF line_count < 2 THEN RAISE EXCEPTION 'FIN_JOURNAL_REQUIRES_TWO_LINES'; END IF;
  IF currency_count <> 1 THEN RAISE EXCEPTION 'FIN_CURRENCY_MISMATCH'; END IF;
  IF debit_total <> credit_total THEN RAISE EXCEPTION 'FIN_UNBALANCED_JOURNAL:%:%', debit_total, credit_total; END IF;

  UPDATE ledger.journal_entry
  SET status = 'posted', posted_by = p_posted_by, posted_at = now()
  WHERE tenant_id = target.tenant_id
    AND legal_entity_id = target.legal_entity_id
    AND journal_entry_id = target.journal_entry_id
  RETURNING * INTO target;
  RETURN target;
END;
$$;

CREATE OR REPLACE FUNCTION ledger.close_period(p_fiscal_period_id uuid, p_principal text) RETURNS ledger.fiscal_period
LANGUAGE plpgsql SECURITY DEFINER SET search_path = ledger, pg_temp AS $$
DECLARE target ledger.fiscal_period;
BEGIN
  UPDATE ledger.fiscal_period
  SET status = 'closed', closed_by = p_principal, closed_at = now(), reopened_by = NULL, reopened_at = NULL
  WHERE tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid
    AND fiscal_period_id = p_fiscal_period_id
    AND status = 'open'
  RETURNING * INTO target;
  IF target.fiscal_period_id IS NULL THEN RAISE EXCEPTION 'FIN_INVALID_PERIOD_STATE'; END IF;
  RETURN target;
END;
$$;

CREATE OR REPLACE FUNCTION ledger.reopen_period(p_fiscal_period_id uuid, p_principal text, p_reason text) RETURNS ledger.fiscal_period
LANGUAGE plpgsql SECURITY DEFINER SET search_path = ledger, pg_temp AS $$
DECLARE target ledger.fiscal_period;
BEGIN
  IF length(trim(p_reason)) < 8 THEN RAISE EXCEPTION 'FIN_REOPEN_REASON_REQUIRED'; END IF;
  UPDATE ledger.fiscal_period
  SET status = 'open', reopened_by = p_principal, reopened_at = now(), reopen_reason = trim(p_reason)
  WHERE tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid
    AND fiscal_period_id = p_fiscal_period_id
    AND status = 'closed'
    AND closed_by <> p_principal
  RETURNING * INTO target;
  IF target.fiscal_period_id IS NULL THEN RAISE EXCEPTION 'FIN_INVALID_PERIOD_STATE_OR_SOD'; END IF;
  RETURN target;
END;
$$;

DO $rls$
DECLARE table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY['book','fiscal_period','account','dimension','posting_rule_version','journal_entry','journal_line'] LOOP
    EXECUTE format('ALTER TABLE ledger.%I ENABLE ROW LEVEL SECURITY', table_name);
    EXECUTE format('ALTER TABLE ledger.%I FORCE ROW LEVEL SECURITY', table_name);
    EXECUTE format('DROP POLICY IF EXISTS %I ON ledger.%I', table_name || '_tenant_policy', table_name);
    EXECUTE format(
      'CREATE POLICY %I ON ledger.%I FOR ALL TO app_runtime USING (tenant_id = NULLIF(current_setting(''app.tenant_id'', true), '''')::uuid) WITH CHECK (tenant_id = NULLIF(current_setting(''app.tenant_id'', true), '''')::uuid)',
      table_name || '_tenant_policy', table_name
    );
  END LOOP;
END
$rls$;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ledger TO app_runtime;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA ledger TO app_runtime;
GRANT EXECUTE ON FUNCTION ledger.post_journal_entry(uuid, text) TO app_runtime;
GRANT EXECUTE ON FUNCTION ledger.close_period(uuid, text) TO app_runtime;
GRANT EXECUTE ON FUNCTION ledger.reopen_period(uuid, text, text) TO app_runtime;

INSERT INTO platform.schema_migration (migration_id, stream_id, description)
VALUES ('202607280101_FIN-01_ledger', 'FIN-01', 'Immutable tenant-scoped double-entry ledger, periods, accounts and posting rules')
ON CONFLICT (migration_id) DO NOTHING;
